### ISSUE TITLE
Erasure coded objects layer

### ISSUE THREAD

**Issue by sanderpick** [recallnet/ipc#125]
## Design

The erasure coded objects layer should likely be designed as a multi-tier system. Objects at the top level, erasure coded eDAGs in the middle layer, and the "raw" block store at the base layer. That way, we interact with files, which can be automatically repaired etc at the API layer.

## Tasks

- [x] Simplified data chunking and networking layer
    We should migrate away from the default IPFS chunking and IPLD (UnixFS) structure to a much simpler and stream-friendly default encoding. Ideally, this is [blake3](https://github.com/BLAKE3-team/BLAKE3) based, ideally we can still use IPLD on-chain, but we should optimize for efficiency, authenticated range requests, speed of ingest, and ease of implementation. Iroh assumes blake3 [binary numeral tree](https://eprint.iacr.org/2021/038) structured data, and there are a lot of really nice reasons we should adopt this as well.
- [x] Basic data entanglement / erasure coding
    A single cylindrical helical lattice which entangles *all data*. All data should be entangled with the prior entangled data on ingress. All nodes should perform this work, and come to consensus on the state transition as per normal. The state root data structure should be updated to include the raw input data DAG commitment, plus the alpha (default to 3) eDAG root commitments.
- [ ] Asymmetrically sized storage clusters
    Nodes can post their storage capacity, and will handle up to this relative proportion of the overall lattice. This capacity should be mutable, and they will automatically start to reallocate portions of the lattice to compensate.
- [ ] Entanglement within retention groups
    The entanglement process should be updated to support pseudorandom entanglement with blocks from within the appropriate retention group. In this case, pseudorandom selection should be based on the hash of the previous blockchain block and the previous blockchain block’s height. Alternative pseudorandom functions should also be tested and explored.
