### ISSUE TITLE
Public testnet feature completeness

### ISSUE THREAD

**Issue by sanderpick** [recallnet/ipc#128]
We can begin an audit when these features are complete.

### Credits

- [x]  Buy credit with HOKU
    - [x]  Pre-buy
    - [x]  Buy “inline” with a transaction
- [x]  Approve credit for others
    - [x]  With and without TTL
    - [x]  With and without limit
- [x]  Revoke credit for others
- [x]  Use credit to pay for transaction gas
- [x]  All available from SDK and solidity contracts

### Blobs

- [x]  Add blobs from other actors, e.g., a bucket
- [x]  Add blobs paid for with credit
    - [x]  With and without TTL
    - [x]  Underlying blob includes recovery metadata from entanglement
- [x]  Add same blob repeatedly from with same subscriber and different actors and only pay for storage once
- [x]  Delete blobs from other actors, e.g., a bucket
- [x]  Get blob info
- [x]  Read blob bytes by hash from another actor
    - [x]  Full
    - [x]  Partial bytes
- [ ]  All available from solidity contracts (note, adding raw blobs from SDK is not available by design, but should be from contracts so that people can build their own bucket-like / other contracts)

### Buckets

- [x]  Create buckets
- [x]  List your buckets
- [x]  Store objects paid for with credit
    - [x]  Under a key
    - [x]  With and without TTL
    - [x]  With metadata
        - [x]  With content-type
    - [ ]  ~Objects are encrypted with client encryption key~
- [x]  Download objects
    - [x]  From SDK
    - [x]  Using the Object API, which can render content-type
    - [x]  Using byte ranges
- [x]  Query objects in a bucket
- [x]  Delete objects in a bucket
- [x]  All available from SDK and solidity contracts
- [x]  All available over S3 API
- [ ]  ~Read object bytes by key from another actor~
    - [ ]  ~Full~
    - [ ]  ~Partial bytes~

### Timehubs

- [x]  Create/list timehubs
- [x]  Crud ops (push, get, count, peaks, root)
- [x]  Store timestamp alongside stored value
- [x]  Restrict API to accepting CIDs only
- [x]  SDK/CLI changes
- [x]  Access control

### Validation

- [x]  Stake HOKU
- [ ]  ~Pledge storage capacity~
- [ ]  Earn rewards from staking
- [ ]  ~Earn rewards from storing data~
- [x]  Unstake
- [ ]  ~Unpledge storage capacity~
- [ ]  ~Only store portion of blob data required by disperser~

### Misc.

- [ ]  Spin local network with N nodes without Docker from `hoku` CLI
- [x]  Chain explorer based on Blockscout
    - [ ]  Deployed, managed, metrics, etc
- [x]  Contract based token faucet
- [x]  Registrar service on top of token faucet
- [x]  Faucet UI with GH login
- [ ] Pick and set Hoku top-level subnet ChainID
