### ISSUE TITLE
Staking Implementation

### ISSUE THREAD

**Issue by JulissaDantes** [recallnet/ipc#145]
We need to:
- Identify testing infrastructure. We might want to spin subnets to test new functionalities, make sure we can do that.
- See what test coverage we are missing from the already created tests in the ipc repository.
- Implement the missing test cases.

- [x] [Staking Previous Work](https://github.com/hokunet/contracts/issues/2)
- [x] [Delegation Previous Work](https://github.com/hokunet/contracts/issues/3)
- [ ] [Staking without delegation implementation](https://github.com/hokunet/contracts/issues/4)
- [ ] [Staking without delegation testnet deployment](https://github.com/hokunet/contracts/issues/5)
